### ISSUE TITLE
Allow identifier to be more flexible in 2.0

### ISSUE THREAD

**Issue by nickevansuk** [openactive/data-model-validator#100]
Given that identifier is used purely to represent internal and related IDs, and is not expected to make sense out of context of a particular feed, does it make more sense to allow:

- String and Number (as current)
- PropertyValue
- Array of PropertyValue

This allows it to be used for multiple internal IDs and related IDs, and should have minimal effect on data consumers (who are not looking for uniformity in this property, which is already optional)

**Comment by MelanieAbraham** [comment]
@ldodds do you want to include this?

**Comment by nickevansuk** [comment]
Noting here as it was missed as in wrong backlog: https://github.com/openactive/modelling-opportunity-data/issues/137

**Comment by ldodds** [comment]
Am not sure that this will make it into the spec for this version, so can be deferred for now.
