### ISSUE TITLE
Agree error messaging wording

### ISSUE THREAD

**Issue by MelanieAbraham** [openactive/data-model-validator#108]
We need to review and agree the error messages the validator produces, to ensure they're clear. We could consider doing some quick user testing with a few people around that.

**Comment by MelanieAbraham** [comment]
Filter types 'notices, errors, warnings and tips' and 'conformance, data quality and general' need updating to be clearer - e.g. to 'required'. 

The required fields could be used to drive data provider behaviour by making common errors categorised as more severe.

**Comment by MelanieAbraham** [comment]
https://docs.google.com/spreadsheets/d/18P_jL-wmikNpb-SHj31t_HfQiK972hKRg7PConGiuY0/edit?usp=sharing

**Comment by MelanieAbraham** [comment]
@petewalker Nick is working through the spreadsheet from top to bottom - if you run out of other things could you start on this? Estimated completion time Tuesday lunch.

**Comment by nickevansuk** [comment]
This is now complete
