### ISSUE TITLE
Built-in samples

### ISSUE THREAD

**Issue by nickevansuk** [openactive/data-model-validator#122]
To make this validator useful for new users, we should include a selection of use-case specific full-fat examples.

These should include:
- A full-fat Session (which includes everything you'd expect from a class schedule, such as this: https://everyoneactiveuat-openactive.azurewebsites.net/api/sessions), ideally embedded in RPDE
   - Simple: A simple version of this with single subEvents and single offers
   - Advanced: A specialist version of this with multiple subEvents and offers
- A full-fat FacilityUse, ideally embedded in RPDE
- A full-fat Slot, ideally embedded in RPDE
- A full-fat Activity List
- A full fat Collection List (if that's what they're going to be called)
- A full-fat Booking Response (/orders/X)

These should also each have permalink URLs that can be referenced from tutorials and documentation.

With the "JSON loaded from URL in GET parameter" feature, the above could probably be achieved through some hosted JSON on GitHub pages and some links from there in Markdown, but would be nice to have a samples dropdown in the Validator interface, to give beginners a comfortable place to start customising from right there in the interface.

**Comment by MelanieAbraham** [comment]
@ldodds is this something to get in now?

**Comment by nickevansuk** [comment]
It looks like this is really just an "Examples" menu with a list of configurable titles and URLs for each menu item (which could be used to point to permalink URLs via `?url=` from GitHub hosted examples).

We could start with just adding a menu entry for:
- [Example Event](http://validator.openactive.io/?url=https://www.openactive.io/data-models/src/2.0/examples/event_example_1.json)

Noting https://github.com/openactive/data-model-validator/issues/215
