### ISSUE TITLE
Make type error message more intuitive

### ISSUE THREAD

**Issue by nickevansuk** [openactive/data-model-validator#148]
Can we make this error message more intuitive?

`Invalid type, expected one of "ArrayOf#http://schema.org/Text", "ArrayOf#Concept" but found "#skos:Concept"`.

For cases where an array is required but not provided, could we just say (or add) `"activity" must be an array of objects` or similar?

Note specifically that the above error needs to be parsed into:
- "oh right so I need to make it an array"
- OH and it can be an array of _strings_, as looking at schema "http://schema.org/Text" is not some magic type
- Oh and the `Concept` part of "ArrayOf#Concept" means that's the type I need for the object, which needs to go in the "type" property, so I need to add `"type": "Concept"`

We should be able to spell this out better in the error message

**Comment by nickevansuk** [comment]
As an aside, based on the spreadsheet,  "ArrayOf#http://schema.org/Text" is no longer allowed for `activity`, so it should only be `"ArrayOf#Concept"`. However this still applies to anywhere else we're using `http://schema.org/Text` where we really mean "you can stick a string in there"

**Comment by MelanieAbraham** [comment]
#108 for error messaging wording 

but @nickevansuk is there still a part of array0f#concerpt that needs something doing with it?

**Comment by nickevansuk** [comment]
Suggest we word this as:

```
Invalid type, expected one of "ArrayOf#http://schema.org/Text", "ArrayOf#Concept" but found "#skos:Concept".

In simple terms: You can't use `Concept` here. You can either use an array of plain strings, or an array of `Concept`.
```

So include the compiler speak stuff, and a helpful description underneath (where the helpful description maps primitives in [this list](https://schema.org/DataType) to use friendly words like "plain string", "plain number", "plain boolean",  "string containing an ISO 8601 date"?

**Comment by nickevansuk** [comment]
Not sure if this overlaps with the error suggestion here too: https://github.com/openactive/data-model-validator/issues/152
`Expected ISO 8601 format value representing either a Date (e.g. "2018-02-17") or DateTime ("2018-02-17T13:00:00Z"). The value should not exceed the accuracy of the underlying data.`

If they're the same error?

**Comment by nickevansuk** [comment]
Additionally this overlaps with https://github.com/openactive/data-model-validator/issues/216

For this case it should list the subtypes, e.g. "You can either use an array of plain strings, or `Concept`, `ChangingRooms`, `Showers`, `Lockers`, `Towels`, `Creche`, `Parking`" (not a real example, just to illustrate)
