### ISSUE TITLE
Line, col reference confusing

### ISSUE THREAD

**Issue by MelanieAbraham** [openactive/data-model-validator#166]
Errors have a reference like: "Line 7, col 6" , but it isn't clear how these relate to the lines in the json on the left hand side - what does the 'col' reference to? Can this be made clearer or removed?

**Comment by petewalker** [comment]
Col refers to the column number - it's very common in text editors. It's the number of characters from the left that the error has occurred at. Most text editors use it to tell you the current cursor position.

**Sublime (see bottom left)**

![image](https://user-images.githubusercontent.com/453816/44133950-60c3a7a4-a05a-11e8-8a81-b5247d6ac759.png)

**Atom**

<img width="680" alt="screen shot 2018-08-15 at 07 15 09" src="https://user-images.githubusercontent.com/453816/44134069-016b02ba-a05b-11e8-8ae1-f69ecc5eadd8.png">

**Even Notepad has it!**

![image](https://user-images.githubusercontent.com/453816/44134016-b7ed6182-a05a-11e8-9ea8-1eefb922bf29.png)
