### ISSUE TITLE
Missing errors from full list of errors

### ISSUE THREAD

**Issue by MelanieAbraham** [openactive/data-model-validator#168]
http://data-model-validator.herokuapp.com/about this list is supposed to contain all errors, but for example, there was an error url invalid type which doesn't appear (see slack for screenshot)

**Comment by petewalker** [comment]
I assume you're referring to:

<img width="690" alt="screen shot 2018-08-10 at 10 48 44" src="https://user-images.githubusercontent.com/453816/44133804-9a826724-a059-11e8-9742-df18f246d2ca.png">

This error is the same as **FieldsCorrectTypeRule** - there's so many combination of this type of rule, it just displays an example:

![screen shot 2018-08-15 at 07 06 17](https://user-images.githubusercontent.com/453816/44133826-bc5954de-a059-11e8-851b-bb6cb77a0850.png)
