### ISSUE TITLE
Release to openactive domain

### ISSUE THREAD

**Issue by MelanieAbraham** [openactive/data-model-validator#169]
we already have validator.openactive.io - can replace the content on there.

**Comment by nickevansuk** [comment]
Replace validator.openactive.io (assuming RPDE validation is included, as the existing validator there only covers RPDE)

**Comment by petewalker** [comment]
As I'm sure you're aware - I can't action this. Will need to be done by whoever controls the openactive DNS

**Comment by petewalker** [comment]
Now live at https://validator.openactive.io/ - thanks @nickevansuk !
