### ISSUE TITLE
afterTimestamp and afterId

### ISSUE THREAD

**Issue by nickevansuk** [openactive/data-model-validator#178]
The afterTimestamp of the next url should always increase with each new page, UNLESS it is the same as the previous page, in which case the afterId should increase (either numerically if it can be parsed to an int, or lexicographically if not)

**Comment by ldodds** [comment]
Or its the last page, in which case neither will change?

**Comment by petewalker** [comment]
Is this still an issue now? I fixed this in the deployment about an hour ago.

**Comment by nickevansuk** [comment]
Hard to debug this... suggest that we amend the error of `The afterTimestamp of the next url should always increase with each new page.` to include something like `The next url of this page is "https://api.clubspark.uk/odi/public/courses?afterTimestamp=1533083636933&afterID=f06eb0cd-2048-476c-a314-0c8be6b0273d"`

**Comment by nickevansuk** [comment]
It looks like it might be fixed, and that it's just that https://api.clubspark.uk/odi/public/courses is broken because they're ID sort is backwards...

It's really amazing how many different ways of incorrectly implementing the spec there are...!

**Comment by petewalker** [comment]
And they're using `afterID` rather than `afterId`

**Comment by petewalker** [comment]
Query string parameters are case-sensitive

**Comment by nickevansuk** [comment]
I saw that error the validator generates, great catch!

**Comment by petewalker** [comment]
RE: debug message - it's actually currently comparing backwards rather than forwards (which might explain your confusion). i.e. storing the params of the previous URL, and comparing that with the current URL.
I can change the direction - otherwise your proposed message change doesn't make sense
