### ISSUE TITLE
Allow configurable X pages

### ISSUE THREAD

**Issue by nickevansuk** [openactive/data-model-validator#181]
Add a slider or similar that allows the number of pages checked to be configured, and checks up to say 500 pages.

Idea is that it default to 20, but when a developer is done they can whack it up to 500, go make a cup of coffee, and come back with a green tick that says they've done a good job.

**Comment by petewalker** [comment]
I'm not sure I like this. Do we really want processes running for that long on the server? 500 pages is a lot.

**Comment by nickevansuk** [comment]
Ah is it a single process that runs? Didn't know whether the client maintained state and just made calls to the server for each page

**Comment by petewalker** [comment]
No - the [openactive/rpde-validator](https://github.com/openactive/rpde-validator) lib is self-contained... some of the rules require walking the feed in order to work anyway.
e.g. Duplicate item checks / deleted item checks.

**Comment by petewalker** [comment]
(Yes, it is a single process that runs. The client knows the progress via a WebSocket)

**Comment by nickevansuk** [comment]
Ah of course, fair enough. 20 pages ~= 40 seconds for a medium-speed one, so it could take 25 minutes or something...

Trying to think of another way to spot-check different parts of the feed and not just rely totally on the first 20 pages... 

Perhaps if we identify it's a unix timestamp we could have buttons for "start from first page modified last month", "start from first page modified last week", start from pages modified today. Doesn't really work for change number though.

**Comment by ldodds** [comment]
I think spot checking or walking through entire feeds is outside of our core use case: checking an initial implementation is conformant.

I've sooner we just make it clear about how many pages we are checking and have a separate configuration property for ourselves to set page sizes.
