### ISSUE TITLE
Add time remaining for validation to complete

### ISSUE THREAD

**Issue by nickevansuk** [openactive/data-model-validator#182]
Also add a simple calculation of time remaining on validation based on:

> ((time elapsed / number of pages checked so far) * number of total pages) - time elapsed

And update this on each page returned

**Comment by ldodds** [comment]
This seems like a reasonable thing to allow for slower feeds

**Comment by petewalker** [comment]
I can implement this - only note that this will probably be inaccurate most of the time, as the number of total pages we're processing is unknown - we only know the maximum.

Most of the feeds I've tested don't have 20 pages to traverse.

**Comment by ldodds** [comment]
hmm. if we're not able to give an accurate assessment, then just ensuring there's a useful holding status with some indication of progress is OK. Am happy if you want to propose something

**Comment by petewalker** [comment]
The existing page provides a progress bar, and has text updating with the progress.

Given the cap on pages, and that there is also request timeout in the RPDE validator - this should never take many minutes. I'll close for now.

Please reopen if you have a compelling reason for this to be added!
