### ISSUE TITLE
Restrict startDate/endDate to only occur in subEvent items

### ISSUE THREAD

**Issue by lukehesluke** [openactive/data-model-validator#186]
This is very related to this modelling-opportunity-data issue: https://github.com/openactive/modelling-opportunity-data/issues/117

We get a validator error if we have an Event which doesn't have a startDate/endDate even though that would be meaningless for it as it has multiple subEvent items and therefore not "one" startDate

While we wait for the spec to potentially update to cater for this type of situation, would it be possible to have some way to relax the startDate requirement on top-level Event?

**Comment by MelanieAbraham** [comment]
@ldodds - can we include this in this version of the validator?

**Comment by nickevansuk** [comment]
This is related to the inheritance bug at https://github.com/openactive/data-model-validator/issues/198, as if inheritance is working properly it shouldn't be required for the parent event if there are subEvents.

**Comment by nickevansuk** [comment]
This can be resolved in this version.

Note that `startDate` and `endDate` are not required or recommended on `SessionSeries` (they don't mean anything at that level), and if they are present on `SessionSeries` they should be dates only (they should not include a time component).

**Comment by petewalker** [comment]
@nickevansuk I'm confused - the example you've pointed to **has** a `startDate` and an `endDate`

Additionally, the spec explicitly says:

>This specification defines several sub-types of Event. These are described in the following sections. Unless otherwise specified:
>* properties have the same status (e.g. `REQUIRED`) as for the generic type

It doesn't say anywhere in the spec that the required / recommended status of `startDate` or `endDate` varies for any of the event types.

**Comment by nickevansuk** [comment]
Great spot, the spec needs to be fixed in this case. Have raised as https://github.com/openactive/modelling-opportunity-data/issues/138
