### ISSUE TITLE
Error messages and general use of "http"

### ISSUE THREAD

**Issue by nickevansuk** [openactive/data-model-validator#197]
If we are recommending `https://openactive.io/*` (https://github.com/openactive/modelling-opportunity-data/issues/120) instead of `http://openactive.io/*` we should be recommending `https://schema.org/*` consistently to match.

So replace all instances of "http" with "https", especially in errors such as `Invalid type, expected "http://schema.org/Duration" but found "http://schema.org/Text".`

**Comment by petewalker** [comment]
I'm making this change, but be aware that schema.org's own JSON-LD file uses http://

https://schema.org/version/3.4/schema.jsonld

```
{
  "@context": {
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "xsd": "http://www.w3.org/2001/XMLSchema#"
  },
  "@graph": [
    {
      "@id": "http://schema.org/CafeOrCoffeeShop",
      "@type": "rdfs:Class",
      "rdfs:comment": "A cafe or coffee shop.",
      "rdfs:label": "CafeOrCoffeeShop",
      "rdfs:subClassOf": {
        "@id": "http://schema.org/FoodEstablishment"
      }
    },
    // ...
  ]
}
```

**Comment by nickevansuk** [comment]
Really good spot! Flagging to @ldodds in case this changes our approach here, though the schema.org FAQ suggests a future move to `https` (https://schema.org/docs/faq.html#19) to perhaps good to be ahead of them in this respect?

**Comment by petewalker** [comment]
@nickevansuk @ldodds 

Additionally, for this to be consistent, we would need to update the spec here:

https://www.openactive.io/modelling-opportunity-data/EditorsDraft/#namespaces

So that `schema` is mapped to `https://schema.org/` as well.

Also bear in mind that this will cause errors like this:

>Value "http://schema.org/EventScheduled" is not in the allowed values for this field. Should be one of "https://schema.org/EventCancelled", "https://schema.org/EventPostponed", "https://schema.org/EventRescheduled", "https://schema.org/EventScheduled".

**Comment by petewalker** [comment]
Or do we want to treat `http` and `https` as equivalent in these cases?

**Comment by nickevansuk** [comment]
Suggest as in other places where we're creating uniformity that we are strict on conformance here, as allowing both will be more work for data consumers.

**Comment by petewalker** [comment]
This has been completed
