### ISSUE TITLE
Rule: Event should not have an eventSchedule or subEvent

### ISSUE THREAD

**Issue by petewalker** [openactive/data-model-validator#207]
* **Target Model(s):** Event
* **Target Field(s):** eventSchedule / subEvent
* **Severity:** Warning
* **Category:** Data Quality

**Comment by petewalker** [comment]
@ldodds @nickevansuk 

This rule seems to conflict with:

>Event **MUST** provide either `schema:startDate` OR `schema:eventSchedule`

**Comment by ldodds** [comment]
There's no conflict here. 

Its a failure if an Event doesn't have a startDate or an eventSchedule.

We just want to have a warning to say if you have an eventSchedule and/or a subEvent on an object of type `Event` then check that you're using the right type: should you be using the `Event` type or the more specific `SessionSeries` type? Maybe this can just be an informational message instead. E.g. "did you know this more specific type is available"?

**Comment by petewalker** [comment]
Okay, makes sense - will move back to backlog!

**Comment by nickevansuk** [comment]
> Its a failure if an Event doesn't have a startDate or an eventSchedule.

To clarify this, the rules are not inherited, so:
- It's a failure if an Event doesn't have a startDate, or an eventSchedule, _or a subEvent_.
- It's a failure if an SessionSeries doesn't have an eventSchedule or a subEvent.
- It's a failure if a ScheduledSession has either a eventSchedule or a subEvent.
- It's a failure if an ScheduledSession doesn't have a startDate.
- It's a failure if a HeadlineEvent doesn't have a startDate (which may just be a date, not a datetime)

Additionally (as above):
- It's a warning if an Event has an eventSchedule and/or a subEvent - "did you know this more specific type is available"?
- Note that `startDate`, `endDate` are not required or recommended on SessionSeries (https://github.com/openactive/data-model-validator/issues/186#issuecomment-417739844)

**Comment by nickevansuk** [comment]
(See also https://github.com/openactive/modelling-opportunity-data/issues/138)

**Comment by petewalker** [comment]
>To clarify this, the rules are not inherited, so:

This is not clearly reflected in the spec :(

>* It's a failure if an Event doesn't have a startDate, or an eventSchedule, _or a subEvent._

The requirement for a subEvent at Event level is also not in the spec.

>* It's a failure if a ScheduledSession has either a eventSchedule or a subEvent

This requirement is not in the spec, and there are examples of a ScheduledSession with an eventSchedule within it

>* It's a failure if a SessionSeries doesn't have an eventSchedule or a subEvent

As an FYI - whilst there's a rule for this in the spreadsheet, it's also not clear that this is an explicit requirement in the spec

As the spec is written now, I'd expect the rules to be:

* It's a failure if an Event doesn't have a startDate, or an eventSchedule
* It's a failure if a SessionSeries doesn't have a startDate, or an eventSchedule
* It's a failure if a SessionSeries doesn't have an eventSchedule or a subEvent **- in spreadsheet but not in spec**
* It's a failure if a ScheduledSession doesn't have a startDate, or an eventSchedule
* It's a failure if a HeadlineEvent doesn't have a startDate, or an eventSchedule
* It's a failure if a HeadlineEvent has an eventSchedule

**Comment by nickevansuk** [comment]
> This requirement is not in the spec, and there are examples of a ScheduledSession with an eventSchedule within it

Just looking at the spec, these are certainly bugs, see PR https://github.com/openactive/modelling-opportunity-data/pull/139

The rest should hopefully be cleared up by: https://github.com/openactive/modelling-opportunity-data/issues/138
