### ISSUE TITLE
Note this error can occur for misplaced properties too

### ISSUE THREAD

**Issue by nickevansuk** [openactive/data-model-validator#245]
## Amend Error (add text in bold)
"If you are trying to use a recognised property, please check the spelling **and ensure that you are using it within the correct object "type".**"

## Original Error
![screen shot 2018-09-08 at 18 20 47](https://user-images.githubusercontent.com/2616208/45256841-f95d3600-b393-11e8-8e2b-e9b0211c970e.png)

**Comment by MelanieAbraham** [comment]
@nickevansuk we still want the final sentence, correct? So should read:

"If you are trying to use a recognised property, please check the spelling and ensure that you are using it within the correct object "type". Otherwise if you are trying to add your own property, simply rename..."

**Comment by nickevansuk** [comment]
Yes that’s right!
