### ISSUE TITLE
Missing error to correct "/"

### ISSUE THREAD

**Issue by nickevansuk** [openactive/data-model-validator#280]
I thought I'd seen this error appear previously, but can we add a new rule if it's not there already?

All OpenActive Activity List IDs should be prefixed in `https://openactive.io/activity-list#` (note the missing "/" after "activity-list". which removed in 2.0).

```
    {
      "type": "Concept",
      "id": "https://openactive.io/activity-list/#2a41c553-84be-4970-b3d0-42f9ef6bd9a4",
      "prefLabel": "Road Cycling",
      "inScheme": "https://openactive.io/activity-list"
    }
```

**Comment by nickevansuk** [comment]
Ah in that case it doesn't seem to error if "/" missing - great if it's data driven as data will be updated later, but doesn't seem to error?

If the activity list validation was working, we'd expect an error from this right?

```
    {
      "type": "Concept",
      "id": "https://openactive.io/activity-list#2a41c553-84be-4970-b3d0-42f9ef6bd9a4",
      "prefLabel": "Road Cycling",
      "inScheme": "https://openactive.io/activity-list"
    }
```

**Comment by petewalker** [comment]
Yeah, the rule seems to match on `id` OR `prefLabel` OR `notation` - if one of those is matched to an item in the activity list, the rule passes.

So... if it matches on `prefLabel`, but the `id` doesn't match, it should fail?
