### ISSUE TITLE
Erroneous 404 error reported on non-OA properties

### ISSUE THREAD

**Issue by nickevansuk** [openactive/data-model-validator#298]
Any context 404 errors will show up on all non-OA properties (as the rule is running and validating all contexts each time? Suggest checking the rule that produces this errors to ensure it doesn't error on all non-OA fields, only on context load? It can't know which context is expecting to match which field if the load fails so better to just error once for @context only.).

![screen shot 2018-10-05 at 01 07 34](https://user-images.githubusercontent.com/2616208/46509597-9f894800-c83b-11e8-90d7-30def2faa992.png)

```
        "@context": [
          "https://www.openactive.io/ns/oa.jsonld",
          "https://www.openactive.io/ns-beta/oa.jsonld"
        ],
        "leader": {
          "type": "Person",
          "givenName": "Smith",
          "jobTitle": "Communication and Event Leader",
          "email": "test@example.com"
        }
```

**Comment by thill-odi** [comment]
Cannot reproduce.

**Comment by nickevansuk** [comment]
Agreed appears to no longer be an issue
