### ISSUE TITLE
Synchronous IO may cause issues with event loop

### ISSUE THREAD

**Issue by lukehesluke** [openactive/data-model-validator#314]
Hi,

I've just been looking through the code and noticed that there are synchronous IO calls that:

- Read/write from/to a filesystem cache
- Make HTTP requests when `loadRemoteJson: true`

These are all synchronous calls which means that the event loop will be blocked until they finish. If anyone is using this code per-request in a server or per-item in a pipeline may start to get serious bottleneck issues.

I suggest that the `.validate()` function returns a promise regardless of whether `loadRemoteJson`. Then, all IO calls (files and http) can be replaced with asynchronous versions

**Comment by nickevansuk** [comment]
This was resolved by https://github.com/openactive/data-model-validator/pull/319
