### ISSUE TITLE
Fatal error caused by { or }

### ISSUE THREAD

**Issue by nickevansuk** [openactive/data-model-validator#348]
Validator crashes when `{` and `}` characters are found in strings in a particular order

```
{
  "@context": "https://openactive.io/",
  "@type": "Event",
  "description": "{description}{something-else}."
}
```

This returns: `Internal validator error: undefined`

**Comment by Lathrisk** [comment]
@nickevansuk (cc: @thill-odi ) is this still an issue? I have tried to replicate this and I don't get the `Internal validator error`, but I do get a set of failures on the validate function, i.e.: 

```
1) validate validate() should return no errors for a valid Event
  Message:
    {"expressionText":"something-else","message":"illegal character","character":"-","position":9} thrown
```

but this seems to be an issue with the dash, not the braces themselves. If I remove the dash then all tests pass.

If this is still an issue, could you provide more information so that I can replicate the error? Thanks.

**Comment by nickevansuk** [comment]
Sure, [click here](https://validator.openactive.io/?version=2.0&validationMode=RPDEFeed#/json/ewogICJAY29udGV4dCI6ICJodHRwczovL29wZW5hY3RpdmUuaW8vIiwKICAiQHR5cGUiOiAiRXZlbnQiLAogICJkZXNjcmlwdGlvbiI6ICJ7ZGVzY3JpcHRpb259e3NvbWV0aGluZy1lbHNlfS4iCn0) to reproduce - perhaps it's an issue with the UI in fact?

**Comment by nickevansuk** [comment]
Though if it's a UI issue, perhaps we put this down in the priority list against the other issues for now? This could be a rabbit hole and there's loads of other important stuff in the backlog

**Comment by nickevansuk** [comment]
In fact I can confirm the source is here:

https://github.com/openactive/data-model-validator-site/blob/6205c8e140807f1e34526800cedabd1e1788516e/src/server/server.js#L217-L228

```javascript
      } catch (e) {
        console.error(e);
        res.status(400).json({
          json: parsedJson,
          response: [{
            category: 'internal',
            severity: 'failure',
            path: '$',
            message: `Internal validator error: ${e.message}`,
          }],
        });
      }
```

Very strange

**Comment by nickevansuk** [comment]
Further investigation: I think I've found the issue:

https://github.com/openactive/data-model-validator/blob/83115aef88bf8ec3a3fe40145ac5e589e530c628/src/classes/field.js#L162-L178

```javascript
 if (!isEnum) {
          // Is this a URL template?
          // This processes most strings... so could be a bit intensive
          const template = UriTemplate.parse(data);
          let isUrlTemplate = false;
          for (const expression of template.expressions) {
            if (expression.constructor.name === 'VariableExpression') {
              isUrlTemplate = true;
              break;
            }
          }
          if (isUrlTemplate) {
            returnType = 'https://schema.org/Text';
          } else if (this.constructor.URL_REGEX.test(data)) {
            returnType = 'https://schema.org/URL';
          }
        }
```

**Comment by nickevansuk** [comment]
As I was so close to this have just finished it off in #375 to get you some time back
