### ISSUE TITLE
Geo coordinates must be floats

### ISSUE THREAD

**Issue by thill-odi** [openactive/data-model-validator#369]
`geo.latitude` and `geo.longitude` need to be expressed as floats with a minimum precision of four decimal places. They MUST NOT be rounded to integers.

**Comment by Lathrisk** [comment]
I noticed that this issue states that the precision should be 4 decimal places, but the [OpenActive spec](https://openactive.io/modelling-opportunity-data/#describing-geographic-location) specifies 2 decimal places.

**Comment by Lathrisk** [comment]
And to mix that up a little more, there is already a [precision rule](https://github.com/openactive/data-model-validator/blob/51b758f0f56442029b5893d9138e7f7d42e14faf/src/rules/core/precision-rule.js#L19) that covers latitude (not longitude) that is to 3 decimal places.

**Comment by nickevansuk** [comment]
I was just about to comment on this issue @Lathrisk but you beat me to it with your discovery of the [precision rule](https://github.com/openactive/data-model-validator/blob/51b758f0f56442029b5893d9138e7f7d42e14faf/src/rules/core/precision-rule.js#L19) - the issue itself is in fact largely redundant, though hopefully still a good academic exercise to get your head into the codebase.

`minDecimalPlaces` currently displays a notice that covers the requirement here, and is only used for `latitude` and `longitude`.

The reason this is a notice and not an error or warning is that some data does actually legitimately have 1, 2 or 3 decimal places. Limited historical context: https://github.com/openactive/developer-microsite/issues/39

A real example:
> Stevenage Swimming Centre, St George's Way, Stevenage, Hertfordshire, SG1 1XY, United Kingdom
> 51.9047222, -0.2

https://github.com/openactive/data-models/blob/2acafeed5636973d38e4c456ca035fdd683ecf18/versions/2.x/models/GeoCoordinates.json#L21-L40

```json
    "latitude": {
      "fieldName": "latitude",
      "sameAs": "https://schema.org/latitude",
      "requiredType": "https://schema.org/Number",
      "minDecimalPlaces": 3,
      "example": 51.522338,
      "description": [
        "The latitude of a location. For example 51.522338 (WGS 84)."
      ]
    },
    "longitude": {
      "fieldName": "longitude",
      "sameAs": "https://schema.org/longitude",
      "requiredType": "https://schema.org/Number",
      "minDecimalPlaces": 3,
      "example": -0.083437,
      "description": [
        "The longitude of a location. For example -0.083437 (WGS 84)."
      ]
    }
```

**Comment by Lathrisk** [comment]
Thanks for the update, Nick. That makes sense. It's been a good introduction to the validator, the spec, and the models!

**Comment by nickevansuk** [comment]
Closing this based on the above
