### ISSUE TITLE
Sprint planning 16 July

### ISSUE THREAD

**Issue by MelanieAbraham** [openactive/data-model-validator#4]
Today we reviewed the prototype. We agreed that there should be a single repository - Leigh is to set this up & Pete will repoint the microsite to this. 

For the next sprint Pete will build out the UI so there is a demonstrable product. Joe will give a UX walk through on Wednesday. 

Pete will also build out the rules within the prototype with:

-  core validation: looking at issue 78 on the spec. Leigh is hoping to make an editor's draft of 2.0 this week, but in the meantime will provide a spreadsheet of the changes required

- a test complex rule: ‘is this a bookable event’?

We agreed when someone uses a property type from schema.org which is not in the spec, we will display a warning to let them know; and where someone uses an unknown model type (e.g. with a typo), the validator will still look into the code and do the validation that it can.

**Comment by petewalker** [comment]
Moved to https://github.com/openactive/data-model-validator/wiki
