### ISSUE TITLE
Validator not picking up faulty URLs

### ISSUE THREAD

**Issue by oliversisman** [openactive/data-model-validator#401]
A change was made to the Open Sessions feed so that it includes an organisations facebook url, twitter handle etc.

This information was in the data feed, which was passing the validator, however wasn't being picked up by the imin platform.  It seems the reason for this was that the data contained faulty urls.

We have updated Open Sessions so that all faulty urls are fixed / faulty urls cant be published in the feed.  

However, the fact it was initially passing the validator made it difficult to spot the issue.

**Comment by nickevansuk** [comment]
Thanks for raising this @oliversisman - do you have examples of the faulty URLs that weren't being picked up?

**Comment by oliversisman** [comment]
Below are the examples of faulty URL's filled by users:

"http://www.abcorganisation",
"@https://facebook.com/@ABC",
"https://twitter/@ABC",
"http://www.instagram.com/@www.instagram.com/ABC@/" 

(example URLs i.e. ABC would have been another organisations name)

**Comment by nickevansuk** [comment]
Hi @oliversisman just checking these examples:

1. "http://www.abcorganisation" - [example in validator](https://validator.openactive.io/?version=2.x&validationMode=RPDEFeed#/json/ewogICJuZXh0IjogImh0dHBzOi8vd3d3LmV4YW1wbGUuY29tL2FwaS9ycGRlL3NjaGVkdWxlZC1zZXNzaW9ucz9hZnRlclRpbWVzdGFtcD0xNTIxNTY1NzE5JmFmdGVySWQ9QzVFRTFFNTUtMkRFNi00NEY3LUE4NjUtNDJGMjY4QTgyQzYzIiwKICAiaXRlbXMiOiBbCiAgICB7CiAgICAgICJzdGF0ZSI6ICJ1cGRhdGVkIiwKICAgICAgImtpbmQiOiAiU2NoZWR1bGVkU2Vzc2lvbiIsCiAgICAgICJpZCI6ICJDNUVFMUU1NS0yREU2LTQ0RjctQTg2NS00MkYyNjhBODJDNjMiLAogICAgICAibW9kaWZpZWQiOiAxNTIxNTY1NzE5LAogICAgICAiZGF0YSI6IHsKICAgICAgICAiQGNvbnRleHQiOiAiaHR0cHM6Ly9vcGVuYWN0aXZlLmlvLyIsCiAgICAgICAgIkB0eXBlIjogIlNjaGVkdWxlZFNlc3Npb24iLAogICAgICAgICJAaWQiOiAiaHR0cHM6Ly9vcGVuc2Vzc2lvbnMuaW8vYXBpL3Nlc3Npb24tc2VyaWVzLzE0MDJDQlAyMDE1MDIxNyMvc3ViRXZlbnQvQzVFRTFFNTUtMkRFNi00NEY3LUE4NjUtNDJGMjY4QTgyQzYzIiwKICAgICAgICAiaWRlbnRpZmllciI6ICJDNUVFMUU1NS0yREU2LTQ0RjctQTg2NS00MkYyNjhBODJDNjMiLAogICAgICAgICJzdXBlckV2ZW50IjogImh0dHBzOi8vb3BlbnNlc3Npb25zLmlvL2FwaS9zZXNzaW9uLXNlcmllcy8xNDAyQ0JQMjAxNTAyMTciLAogICAgICAgICJzdGFydERhdGUiOiAiMjAxNi0wNS0wOVQxODoxNTowMFoiLAogICAgICAgICJlbmREYXRlIjogIjIwMTYtMDUtMDlUMTk6MTU6MDBaIiwKICAgICAgICAiZHVyYXRpb24iOiAiUFQxSCIsCiAgICAgICAgImV2ZW50U3RhdHVzIjogImh0dHBzOi8vc2NoZW1hLm9yZy9FdmVudFNjaGVkdWxlZCIsCiAgICAgICAgIm1heGltdW1BdHRlbmRlZUNhcGFjaXR5IjogMTAsCiAgICAgICAgInJlbWFpbmluZ0F0dGVuZGVlQ2FwYWNpdHkiOiAwLAogICAgICAgICJ1cmwiOiAiaHR0cDovL3d3dy5hYmNvcmdhbmlzYXRpb24iCiAgICAgIH0KICAgIH0KICBdLAogICJsaWNlbnNlIjogImh0dHBzOi8vY3JlYXRpdmVjb21tb25zLm9yZy9saWNlbnNlcy9ieS80LjAvIgp9) - VALID
2. "@https://facebook.com/@ABC"  - [example in validator](https://validator.openactive.io/?version=2.x&validationMode=RPDEFeed#/json/ewogICJuZXh0IjogImh0dHBzOi8vd3d3LmV4YW1wbGUuY29tL2FwaS9ycGRlL3NjaGVkdWxlZC1zZXNzaW9ucz9hZnRlclRpbWVzdGFtcD0xNTIxNTY1NzE5JmFmdGVySWQ9QzVFRTFFNTUtMkRFNi00NEY3LUE4NjUtNDJGMjY4QTgyQzYzIiwKICAiaXRlbXMiOiBbCiAgICB7CiAgICAgICJzdGF0ZSI6ICJ1cGRhdGVkIiwKICAgICAgImtpbmQiOiAiU2NoZWR1bGVkU2Vzc2lvbiIsCiAgICAgICJpZCI6ICJDNUVFMUU1NS0yREU2LTQ0RjctQTg2NS00MkYyNjhBODJDNjMiLAogICAgICAibW9kaWZpZWQiOiAxNTIxNTY1NzE5LAogICAgICAiZGF0YSI6IHsKICAgICAgICAiQGNvbnRleHQiOiAiaHR0cHM6Ly9vcGVuYWN0aXZlLmlvLyIsCiAgICAgICAgIkB0eXBlIjogIlNjaGVkdWxlZFNlc3Npb24iLAogICAgICAgICJAaWQiOiAiaHR0cHM6Ly9vcGVuc2Vzc2lvbnMuaW8vYXBpL3Nlc3Npb24tc2VyaWVzLzE0MDJDQlAyMDE1MDIxNyMvc3ViRXZlbnQvQzVFRTFFNTUtMkRFNi00NEY3LUE4NjUtNDJGMjY4QTgyQzYzIiwKICAgICAgICAiaWRlbnRpZmllciI6ICJDNUVFMUU1NS0yREU2LTQ0RjctQTg2NS00MkYyNjhBODJDNjMiLAogICAgICAgICJzdXBlckV2ZW50IjogImh0dHBzOi8vb3BlbnNlc3Npb25zLmlvL2FwaS9zZXNzaW9uLXNlcmllcy8xNDAyQ0JQMjAxNTAyMTciLAogICAgICAgICJzdGFydERhdGUiOiAiMjAxNi0wNS0wOVQxODoxNTowMFoiLAogICAgICAgICJlbmREYXRlIjogIjIwMTYtMDUtMDlUMTk6MTU6MDBaIiwKICAgICAgICAiZHVyYXRpb24iOiAiUFQxSCIsCiAgICAgICAgImV2ZW50U3RhdHVzIjogImh0dHBzOi8vc2NoZW1hLm9yZy9FdmVudFNjaGVkdWxlZCIsCiAgICAgICAgIm1heGltdW1BdHRlbmRlZUNhcGFjaXR5IjogMTAsCiAgICAgICAgInJlbWFpbmluZ0F0dGVuZGVlQ2FwYWNpdHkiOiAwLAogICAgICAgICJ1cmwiOiAiQGh0dHBzOi8vZmFjZWJvb2suY29tL0BBQkMiCiAgICAgIH0KICAgIH0KICBdLAogICJsaWNlbnNlIjogImh0dHBzOi8vY3JlYXRpdmVjb21tb25zLm9yZy9saWNlbnNlcy9ieS80LjAvIgp9) - INVALID
3. "https://twitter/@ABC"  - [example in validator](https://validator.openactive.io/?version=2.x&validationMode=RPDEFeed#/json/ewogICJuZXh0IjogImh0dHBzOi8vd3d3LmV4YW1wbGUuY29tL2FwaS9ycGRlL3NjaGVkdWxlZC1zZXNzaW9ucz9hZnRlclRpbWVzdGFtcD0xNTIxNTY1NzE5JmFmdGVySWQ9QzVFRTFFNTUtMkRFNi00NEY3LUE4NjUtNDJGMjY4QTgyQzYzIiwKICAiaXRlbXMiOiBbCiAgICB7CiAgICAgICJzdGF0ZSI6ICJ1cGRhdGVkIiwKICAgICAgImtpbmQiOiAiU2NoZWR1bGVkU2Vzc2lvbiIsCiAgICAgICJpZCI6ICJDNUVFMUU1NS0yREU2LTQ0RjctQTg2NS00MkYyNjhBODJDNjMiLAogICAgICAibW9kaWZpZWQiOiAxNTIxNTY1NzE5LAogICAgICAiZGF0YSI6IHsKICAgICAgICAiQGNvbnRleHQiOiAiaHR0cHM6Ly9vcGVuYWN0aXZlLmlvLyIsCiAgICAgICAgIkB0eXBlIjogIlNjaGVkdWxlZFNlc3Npb24iLAogICAgICAgICJAaWQiOiAiaHR0cHM6Ly9vcGVuc2Vzc2lvbnMuaW8vYXBpL3Nlc3Npb24tc2VyaWVzLzE0MDJDQlAyMDE1MDIxNyMvc3ViRXZlbnQvQzVFRTFFNTUtMkRFNi00NEY3LUE4NjUtNDJGMjY4QTgyQzYzIiwKICAgICAgICAiaWRlbnRpZmllciI6ICJDNUVFMUU1NS0yREU2LTQ0RjctQTg2NS00MkYyNjhBODJDNjMiLAogICAgICAgICJzdXBlckV2ZW50IjogImh0dHBzOi8vb3BlbnNlc3Npb25zLmlvL2FwaS9zZXNzaW9uLXNlcmllcy8xNDAyQ0JQMjAxNTAyMTciLAogICAgICAgICJzdGFydERhdGUiOiAiMjAxNi0wNS0wOVQxODoxNTowMFoiLAogICAgICAgICJlbmREYXRlIjogIjIwMTYtMDUtMDlUMTk6MTU6MDBaIiwKICAgICAgICAiZHVyYXRpb24iOiAiUFQxSCIsCiAgICAgICAgImV2ZW50U3RhdHVzIjogImh0dHBzOi8vc2NoZW1hLm9yZy9FdmVudFNjaGVkdWxlZCIsCiAgICAgICAgIm1heGltdW1BdHRlbmRlZUNhcGFjaXR5IjogMTAsCiAgICAgICAgInJlbWFpbmluZ0F0dGVuZGVlQ2FwYWNpdHkiOiAwLAogICAgICAgICJ1cmwiOiAiaHR0cHM6Ly90d2l0dGVyL0BBQkMiCiAgICAgIH0KICAgIH0KICBdLAogICJsaWNlbnNlIjogImh0dHBzOi8vY3JlYXRpdmVjb21tb25zLm9yZy9saWNlbnNlcy9ieS80LjAvIgp9) - INVALID
4. "http://www.instagram.com/@www.instagram.com/ABC@/"  - [example in validator](https://validator.openactive.io/?version=2.x&validationMode=RPDEFeed#/json/ewogICJuZXh0IjogImh0dHBzOi8vd3d3LmV4YW1wbGUuY29tL2FwaS9ycGRlL3NjaGVkdWxlZC1zZXNzaW9ucz9hZnRlclRpbWVzdGFtcD0xNTIxNTY1NzE5JmFmdGVySWQ9QzVFRTFFNTUtMkRFNi00NEY3LUE4NjUtNDJGMjY4QTgyQzYzIiwKICAiaXRlbXMiOiBbCiAgICB7CiAgICAgICJzdGF0ZSI6ICJ1cGRhdGVkIiwKICAgICAgImtpbmQiOiAiU2NoZWR1bGVkU2Vzc2lvbiIsCiAgICAgICJpZCI6ICJDNUVFMUU1NS0yREU2LTQ0RjctQTg2NS00MkYyNjhBODJDNjMiLAogICAgICAibW9kaWZpZWQiOiAxNTIxNTY1NzE5LAogICAgICAiZGF0YSI6IHsKICAgICAgICAiQGNvbnRleHQiOiAiaHR0cHM6Ly9vcGVuYWN0aXZlLmlvLyIsCiAgICAgICAgIkB0eXBlIjogIlNjaGVkdWxlZFNlc3Npb24iLAogICAgICAgICJAaWQiOiAiaHR0cHM6Ly9vcGVuc2Vzc2lvbnMuaW8vYXBpL3Nlc3Npb24tc2VyaWVzLzE0MDJDQlAyMDE1MDIxNyMvc3ViRXZlbnQvQzVFRTFFNTUtMkRFNi00NEY3LUE4NjUtNDJGMjY4QTgyQzYzIiwKICAgICAgICAiaWRlbnRpZmllciI6ICJDNUVFMUU1NS0yREU2LTQ0RjctQTg2NS00MkYyNjhBODJDNjMiLAogICAgICAgICJzdXBlckV2ZW50IjogImh0dHBzOi8vb3BlbnNlc3Npb25zLmlvL2FwaS9zZXNzaW9uLXNlcmllcy8xNDAyQ0JQMjAxNTAyMTciLAogICAgICAgICJzdGFydERhdGUiOiAiMjAxNi0wNS0wOVQxODoxNTowMFoiLAogICAgICAgICJlbmREYXRlIjogIjIwMTYtMDUtMDlUMTk6MTU6MDBaIiwKICAgICAgICAiZHVyYXRpb24iOiAiUFQxSCIsCiAgICAgICAgImV2ZW50U3RhdHVzIjogImh0dHBzOi8vc2NoZW1hLm9yZy9FdmVudFNjaGVkdWxlZCIsCiAgICAgICAgIm1heGltdW1BdHRlbmRlZUNhcGFjaXR5IjogMTAsCiAgICAgICAgInJlbWFpbmluZ0F0dGVuZGVlQ2FwYWNpdHkiOiAwLAogICAgICAgICJ1cmwiOiAiaHR0cDovL3d3dy5pbnN0YWdyYW0uY29tL3d3dy5pbnN0YWdyYW0uY29tL0FCQ0AvIgogICAgICB9CiAgICB9CiAgXSwKICAibGljZW5zZSI6ICJodHRwczovL2NyZWF0aXZlY29tbW9ucy5vcmcvbGljZW5zZXMvYnkvNC4wLyIKfQ) - VALID

As you can see above, half of these examples do actually fail the validator. It might be that you were only running the validator on the first page of your feed? See [here](https://developer.openactive.io/publishing-data/data-feeds/testing-feeds#openactive-test-suite) for instructions on how to run it for your whole feed.

The remaining (1) and (4) examples could be considered valid URLs (though they don't actually resolve to valid web pages, they could in theory do so). It's possible for the validator to check each URL actually resolves to a valid web page, however that would slow down validation considerably (as it would need to load each web page as it was validating).

Hopefully the validator (when run across all pages) provides enough information here to help you spot the issue, even if it isn't comprehensively validating that the web page referred to by the URL actually exists.

**Comment by nickevansuk** [comment]
Closing this for now, but feel free to reopen a separate issue if full URL **verification** (checking the URL actually exists) rather than **validation** (just looking at how the URL is structured) would be helpful!
