### ISSUE TITLE
`Order.seller` must be expanded object in Open Booking API responses

### ISSUE THREAD

**Issue by lukehesluke** [openactive/data-model-validator#406]
## What?

Validate that `seller` (i.e. `Order.seller`, `OrderQuote.seller`, and `OrderProposal.seller`) must be a full object in Open Booking API responses - rather than just `@id` URLs.

* i.e. validator should mark:
    - [this](https://validator.openactive.io/?version=2.x&validationMode=C1Response#/json/ewogICJAY29udGV4dCI6ICJodHRwczovL29wZW5hY3RpdmUuaW8vIiwKICAiQHR5cGUiOiAiT3JkZXJRdW90ZSIsCiAgIkBpZCI6ICJodHRwczovL2V4YW1wbGUuY29tL2FwaS9vcmRlci1xdW90ZXMvZTExNDI5ZWEtNDY3Zi00MjcwLWFiNjItZTQ3MzY4OTk2ZmU4IiwKICAib3JkZXJSZXF1aXJlc0FwcHJvdmFsIjogZmFsc2UsCiAgImJyb2tlclJvbGUiOiAiaHR0cHM6Ly9vcGVuYWN0aXZlLmlvL0FnZW50QnJva2VyIiwKICAiYnJva2VyIjogewogICAgIkB0eXBlIjogIk9yZ2FuaXphdGlvbiIsCiAgICAibmFtZSI6ICJNeUZpdG5lc3NBcHAiLAogICAgInVybCI6ICJodHRwczovL215Zml0bmVzc2FwcC5leGFtcGxlLmNvbSIsCiAgICAiZGVzY3JpcHRpb24iOiAiQSBmaXRuZXNzIGFwcCBmb3IgYWxsIHRoZSBjb21tdW5pdHkiLAogICAgImxvZ28iOiB7CiAgICAgICJAdHlwZSI6ICJJbWFnZU9iamVjdCIsCiAgICAgICJ1cmwiOiAiaHR0cDovL2RhdGEubXlmaXRuZXNzYXBwLm9yZy51ay9pbWFnZXMvbG9nby5wbmciCiAgICB9LAogICAgImFkZHJlc3MiOiB7CiAgICAgICJAdHlwZSI6ICJQb3N0YWxBZGRyZXNzIiwKICAgICAgInN0cmVldEFkZHJlc3MiOiAiQWxhbiBQZWFjb2NrIFdheSIsCiAgICAgICJhZGRyZXNzTG9jYWxpdHkiOiAiVmlsbGFnZSBFYXN0IiwKICAgICAgImFkZHJlc3NSZWdpb24iOiAiTWlkZGxlc2Jyb3VnaCIsCiAgICAgICJwb3N0YWxDb2RlIjogIlRTNCAzQUUiLAogICAgICAiYWRkcmVzc0NvdW50cnkiOiAiR0IiCiAgICB9CiAgfSwKICAic2VsbGVyIjogImh0dHBzOi8vZXhhbXBsZS5jb20vYXBpL29yZ2FuaXNhdGlvbnMvMTIzIiwKICAiYm9va2luZ1NlcnZpY2UiOiB7CiAgICAiQHR5cGUiOiAiQm9va2luZ1NlcnZpY2UiLAogICAgIm5hbWUiOiAiUGxheXdhemUiLAogICAgInVybCI6ICJodHRwOi8vd3d3LnBsYXl3YXplLmNvbSIsCiAgICAidGVybXNPZlNlcnZpY2UiOiBbCiAgICAgIHsKICAgICAgICAiQHR5cGUiOiAiVGVybXMiLAogICAgICAgICJuYW1lIjogIlRlcm1zIG9mIFNlcnZpY2UiLAogICAgICAgICJ1cmwiOiAiaHR0cHM6Ly9icm9rZXJleGFtcGxlLmNvbS90ZXJtcy5odG1sIiwKICAgICAgICAicmVxdWlyZXNFeHBsaWNpdENvbnNlbnQiOiBmYWxzZQogICAgICB9CiAgICBdCiAgfSwKICAibGVhc2UiOiB7CiAgICAiQHR5cGUiOiAiTGVhc2UiLAogICAgImxlYXNlRXhwaXJlcyI6ICIyMDE4LTEwLTAxVDExOjAwOjAwWiIKICB9LAogICJvcmRlcmVkSXRlbSI6IFsKICAgIHsKICAgICAgIkB0eXBlIjogIk9yZGVySXRlbSIsCiAgICAgICJwb3NpdGlvbiI6IDAsCiAgICAgICJ1bml0VGF4U3BlY2lmaWNhdGlvbiI6IFsKICAgICAgICB7CiAgICAgICAgICAiQHR5cGUiOiAiVGF4Q2hhcmdlU3BlY2lmaWNhdGlvbiIsCiAgICAgICAgICAibmFtZSI6ICJWQVQgYXQgMjAlIiwKICAgICAgICAgICJwcmljZSI6IDEsCiAgICAgICAgICAicHJpY2VDdXJyZW5jeSI6ICJHQlAiLAogICAgICAgICAgInJhdGUiOiAwLjIKICAgICAgICB9CiAgICAgIF0sCiAgICAgICJhY2NlcHRlZE9mZmVyIjogewogICAgICAgICJAdHlwZSI6ICJPZmZlciIsCiAgICAgICAgIkBpZCI6ICJodHRwczovL2V4YW1wbGUuY29tL2V2ZW50cy80NTIjL29mZmVycy84NzgiLAogICAgICAgICJkZXNjcmlwdGlvbiI6ICJXaW5nZXIgc3BhY2UgZm9yIFNwZWVkYmFsbC4iLAogICAgICAgICJuYW1lIjogIlNwZWVkYmFsbCB3aW5nZXIgcG9zaXRpb24iLAogICAgICAgICJwcmljZSI6IDEwLAogICAgICAgICJwcmljZUN1cnJlbmN5IjogIkdCUCIsCiAgICAgICAgInZhbGlkRnJvbUJlZm9yZVN0YXJ0RGF0ZSI6ICJQNkQiLAogICAgICAgICJhbGxvd0N1c3RvbWVyQ2FuY2VsbGF0aW9uRnVsbFJlZnVuZCI6IHRydWUsCiAgICAgICAgImxhdGVzdENhbmNlbGxhdGlvbkJlZm9yZVN0YXJ0RGF0ZSI6ICJQMUQiCiAgICAgIH0sCiAgICAgICJvcmRlcmVkSXRlbSI6IHsKICAgICAgICAiQHR5cGUiOiAiU2NoZWR1bGVkU2Vzc2lvbiIsCiAgICAgICAgIkBpZCI6ICJodHRwczovL2V4YW1wbGUuY29tL2V2ZW50cy80NTIvc3ViRXZlbnRzLzEzMiIsCiAgICAgICAgImlkZW50aWZpZXIiOiAxMjMsCiAgICAgICAgImV2ZW50U3RhdHVzIjogImh0dHBzOi8vc2NoZW1hLm9yZy9FdmVudFNjaGVkdWxlZCIsCiAgICAgICAgIm1heGltdW1BdHRlbmRlZUNhcGFjaXR5IjogMzAsCiAgICAgICAgInJlbWFpbmluZ0F0dGVuZGVlQ2FwYWNpdHkiOiAyMCwKICAgICAgICAic3RhcnREYXRlIjogIjIwMTgtMTAtMzBUMTE6MDA6MDBaIiwKICAgICAgICAiZW5kRGF0ZSI6ICIyMDE4LTEwLTMwVDEyOjAwOjAwWiIsCiAgICAgICAgImR1cmF0aW9uIjogIlBUMUgiLAogICAgICAgICJzdXBlckV2ZW50IjogewogICAgICAgICAgIkB0eXBlIjogIlNlc3Npb25TZXJpZXMiLAogICAgICAgICAgIkBpZCI6ICJodHRwczovL2FwaS5leGFtcGxlLmNvbS9ldmVudHMvNDUyIiwKICAgICAgICAgICJuYW1lIjogIkJvZHlwdW1wIiwKICAgICAgICAgICJhY3Rpdml0eSI6IFsKICAgICAgICAgICAgewogICAgICAgICAgICAgICJAdHlwZSI6ICJDb25jZXB0IiwKICAgICAgICAgICAgICAiQGlkIjogImh0dHBzOi8vb3BlbmFjdGl2ZS5pby9hY3Rpdml0eS1saXN0IzVlNzhiY2JlLTM2ZGItNDI1YS05MDY0LWJmOTZkMDljYzM1MSIsCiAgICAgICAgICAgICAgInByZWZMYWJlbCI6ICJCb2R5cHVtcOKEoiIsCiAgICAgICAgICAgICAgImluU2NoZW1lIjogImh0dHBzOi8vb3BlbmFjdGl2ZS5pby9hY3Rpdml0eS1saXN0IgogICAgICAgICAgICB9CiAgICAgICAgICBdLAogICAgICAgICAgImR1cmF0aW9uIjogIlBUMUgiLAogICAgICAgICAgInVybCI6ICJodHRwczovL2V4YW1wbGUuY29tL2V2ZW50cy80NTIiLAogICAgICAgICAgImxvY2F0aW9uIjogewogICAgICAgICAgICAiQHR5cGUiOiAiUGxhY2UiLAogICAgICAgICAgICAidXJsIjogImh0dHBzOi8vd3d3LmV2ZXJ5b25lYWN0aXZlLmNvbS9jZW50cmVzL01pZGRsZXNicm91Z2gtU3BvcnRzLVZpbGxhZ2UiLAogICAgICAgICAgICAibmFtZSI6ICJNaWRkbGVzYnJvdWdoIFNwb3J0cyBWaWxsYWdlIiwKICAgICAgICAgICAgImlkZW50aWZpZXIiOiAiMDE0MCIsCiAgICAgICAgICAgICJhZGRyZXNzIjogewogICAgICAgICAgICAgICJAdHlwZSI6ICJQb3N0YWxBZGRyZXNzIiwKICAgICAgICAgICAgICAic3RyZWV0QWRkcmVzcyI6ICJBbGFuIFBlYWNvY2sgV2F5IiwKICAgICAgICAgICAgICAiYWRkcmVzc0xvY2FsaXR5IjogIlZpbGxhZ2UgRWFzdCIsCiAgICAgICAgICAgICAgImFkZHJlc3NSZWdpb24iOiAiTWlkZGxlc2Jyb3VnaCIsCiAgICAgICAgICAgICAgInBvc3RhbENvZGUiOiAiVFM0IDNBRSIsCiAgICAgICAgICAgICAgImFkZHJlc3NDb3VudHJ5IjogIkdCIgogICAgICAgICAgICB9LAogICAgICAgICAgICAiZ2VvIjogewogICAgICAgICAgICAgICJAdHlwZSI6ICJHZW9Db29yZGluYXRlcyIsCiAgICAgICAgICAgICAgImxhdGl0dWRlIjogNTQuNTQzOTY0LAogICAgICAgICAgICAgICJsb25naXR1ZGUiOiAtMS4yMDk3ODUwMDAwMDAwMQogICAgICAgICAgICB9CiAgICAgICAgICB9CiAgICAgICAgfQogICAgICB9CiAgICB9CiAgXSwKICAidG90YWxQYXltZW50RHVlIjogewogICAgIkB0eXBlIjogIlByaWNlU3BlY2lmaWNhdGlvbiIsCiAgICAicHJpY2UiOiA1LAogICAgInByaWNlQ3VycmVuY3kiOiAiR0JQIgogIH0sCiAgInRvdGFsUGF5bWVudFRheCI6IFsKICAgIHsKICAgICAgIkB0eXBlIjogIlRheENoYXJnZVNwZWNpZmljYXRpb24iLAogICAgICAibmFtZSI6ICJWQVQgYXQgMjAlIiwKICAgICAgInByaWNlIjogMSwKICAgICAgInByaWNlQ3VycmVuY3kiOiAiR0JQIiwKICAgICAgInJhdGUiOiAwLjIKICAgIH0KICBdCn0) invalid due to `"seller": "https://example.com/api/organisations/123"`

## Why?

The [Open Booking API specifies](https://openactive.io/open-booking-api/EditorsDraft/1.0CR3/#schema-organization-or-schema-person-for-seller) that:

> The `seller` must be a `schema:Organization` or `schema:Person` with the following properties, in order for tax receipts to be successfully generated.

(and "the following properties" include things like `taxMode`). So, it is much more difficult or impossible for an Open Booking API client to generate tax receipts successfully if the C1/C2/B/etc responses do not include the expanded seller and thus do not directly include tax receipt related properties.

**Comment by civsiv** [comment]
This is related to (but is the opposite of) https://github.com/openactive/data-model-validator/issues/402
