### ISSUE TITLE
Where fields are not in spec, but are listed in schema.org, display a different warning

### ISSUE THREAD

**Issue by petewalker** [openactive/data-model-validator#5]
Use https://schema.org/version/latest/schema.jsonld to detect properties of objects that are used by producers that are not in the OpenActive specification.

This will allow the messages we show the user to be more informative. Properties that are on https://schema.org, but that aren't in the OpenActive specification could cause confusion to developers if we throw an error simply saying "not in spec".

Suggested error message is something along the lines of:

_This field is listed on https://schema.org, but is not among the recommended fields in the OpenActive Modelling Specification_

**Comment by ldodds** [comment]
We've discussed checking whether fields are defined in schema.org. This is now in #95.

So I suggest we reframe this issue as:

If the data contains fields that are in Schema.org but not in our data models, then the validator should display a note to say something like: 

"The following fields are declared in Schema.org but this validator is  not yet capable of checking whether they have the right format or values. You should refer to the Schema.org documentation for additional guidance".

This gives us a way to be clear to a user about what isn't being checked, but doesn't lead them to think it should be fixed. We might want an "information" type in additional to error, warning, suggestion to distinguish these.

If a field isn't in our data models or Schema.org then it would be an error as per #95. 

This doesn't specifically address custom properties, but we can define rules for those separately.
