### ISSUE TITLE
Publish packages on NPM

### ISSUE THREAD

**Issue by petewalker** [openactive/data-model-validator#84]
* [x] @ldodds creates an npm organisation
* [x] @petewalker publishes data-models as `@openactive/data-models`
* [x] @petewalker publishes data-model-validator as `@openactive/data-model-validator`
* [x] @petewalker publishes rpde-validator as `@openactive/rpde-validator`

**Comment by petewalker** [comment]
Looks like an openactive user exists -> https://www.npmjs.com/org/openactive @ldodds, was that you?

It need to be converted to an organisation. My user will then need to be added - https://www.npmjs.com/org/petewalker

**Comment by ldodds** [comment]
There is now an openactive organisation and both @petewalker and @nickevansuk have been invited as admins.
