### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by MelanieAbraham** [openactive/data-model-validator#85]
We need clear documentation to ensure that the validator becomes self sustaining. 
These include:

- [x] How to use the validator library in different applications (installation, etc):
  - [x] `npm install`
  - [x] Example of use, documentation of options / outputs
- [x] How to contribute new rules

- [x] How to deploy the UX to Heroku
- [x] How to run the UX server locally
- [x] How to modify the base models in openactive/data-models
- [x] How to run the tests in each library

**Comment by petewalker** [comment]
This is blocked on implementing a way for people to ask the library to implement their own rules.

**Comment by MelanieAbraham** [comment]
Note I now removed the 'implement own rules' as we don't require this.

**Comment by petewalker** [comment]
Thanks @MelanieAbraham - marking as closed
