### ISSUE TITLE
Offer.ageRange

### ISSUE THREAD

**Issue by nickevansuk** [openactive/data-model-validator#91]
> Offer.ageRange: Recommended field is missing.

Validator should be smart enough to notice that the ageRange specified in the parent event is already constrained (e.g. it's a kids event), and not request the ageRange for an Offer.

Offer.ageRange is only recommended where the parent event is open to a range of ages (check that the parent event is available for more than one of "kids" (<18), "adults" (18-50), "older adults" (50+).

If the ageRange on the parent Event is narrow, it's assumed that all Offers are for this age group, and the data doesn't need to be repeated.

**Comment by MelanieAbraham** [comment]
@ldodds are we ok to include this in the project?

**Comment by ldodds** [comment]
No, we shouldn't include this in the validator as its not an agreed behaviour according to the specification. This is a different type of inheritance rule than we currently have specified.

@nickevansuk , on the basis that this is new behaviour, then please file a proposal on the modelling spec, if you haven't already. I'm going to close this for now, we can file a new issue based on agreed processing rule.

**Comment by nickevansuk** [comment]
Let's leave for now and see how this works in practice, as it's only recommended not required.
