### ISSUE TITLE
Timezone indicator should not be present on times without dates

### ISSUE THREAD

**Issue by nickevansuk** [openactive/data-model-validator#99]
It doesn't make sense to put a timezone indicator on a time without a date associated, how would you translate it into local time?

This is an error in the existing spec, so just need to remove the need for the timezone component and recommend in the spec that these times are always in local time. If a shop opens it's only really relevant to know when it opens in local time anyway - even if you fly to New York you don't expect to check the JFK airport shop opening times in GMT before you go...

![screen shot 2018-07-26 at 13 28 08](https://user-images.githubusercontent.com/2616208/43266064-4c09abc4-90e2-11e8-9caa-31334bbfa58a.png)

**Comment by MelanieAbraham** [comment]
@ldodds this is now in the 2.0 spec?

**Comment by nickevansuk** [comment]
Yes this has been resolved in spec, so validator should be updated to match for opens, closes, and Schedules: https://www.openactive.io/modelling-opportunity-data/EditorsDraft/#publishing-event-schedules
